spring:
    profiles:
        active: DEV
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            initial-size: 0
            min-idle: 2
            max-active: 2
            max-wait: 1000
            use-unfair-lock: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            test-on-borrow: true
            validation-query: select 1 FROM DUAL
            validation-query-timeout: 2
            test-while-idle: true
            test-on-return: false
server:
    port: 17002
    servlet:
        context-path: /recognize
        session:
            timeout: 1m
            tracking-modes: cookie
logging:
    level:
        org: ERROR
        com: ERROR
        com.hnkc: INFO
mybatis-plus:
    type-aliases-package: com.hnkc.recognize.model
    configuration:
        map-underscore-to-camel-case: true
swagger:
    enable: true
config:
    wordSql: "select distinct(label) from t_refine_option where field_id is not null"
