spring:
  profiles: DEV
  datasource:
    url: jdbc:oracle:thin:@192.168.0.142:1521/hnkcdb
    username: zgh
    password: Created!12
logging:
  level:
    com.hnkc: INFO
config:
  webTitle: 示例程序页面标题

